### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by wyatt-herkamp** [Vatuu/discord-rpc#4] opened 2018-01-11 03:51 UTC
`java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:389)
	at com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:328)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:767)
Caused by: java.lang.UnsatisfiedLinkError: /media/storage/Programming/PersonalProjects/KingTux/null/discord-rpc.jar/discord-rpc.so: /media/storage/Programming/PersonalProjects/KingTux/null/discord-rpc.jar/discord-rpc.so: failed to map segment from shared object
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at net.arikia.dev.drpc.DiscordRPC.loadDLL(DiscordRPC.java:106)
	at net.arikia.dev.drpc.DiscordRPC.<clinit>(DiscordRPC.java:21)
	at me.kingtux.kingtux.Main.main(Main.java:30)
	... 11 more
Exception running application me.kingtux.kingtux.Main
`
Code
```
package me.kingtux.kingtux;

import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import net.arikia.dev.drpc.DiscordEventHandlers;
import net.arikia.dev.drpc.DiscordRPC;
import net.arikia.dev.drpc.DiscordRichPresence;
import net.arikia.dev.drpc.callbacks.ReadyCallback;
import javafx.stage.Stage;

import java.util.Scanner;

public class Main extends Application {

    @Override
    public void start(Stage primaryStage) throws Exception{
        Parent root = FXMLLoader.load(getClass().getResource("window.fxml"));
        primaryStage.setTitle("KingTux.jar");
        primaryStage.setScene(new Scene(root, 600, 275));
        primaryStage.show();
    }


    public static void main(String[] args) {
        System.out.println("Check2");
        DiscordEventHandlers handler = new DiscordEventHandlers();
        handler.ready = new DiscordPresense();
        DiscordRPC.DiscordInitialize("400851884899827714", handler, true);
        DiscordRPC.DiscordRunCallbacks();
        Scanner scanner = new Scanner(System.in);
        launch(args);

    }
}
```

**Comment by Vatuu** [comment] 2018-01-15 21:04
What OS are you using, and what Version?

**Comment by wyatt-herkamp** [comment] 2018-01-16 13:51
I am using Fedora(Linux) 
Version
0.9-beta.4

**Comment by Vatuu** [comment] 2018-01-18 11:48
Is the temp library being created in your temp-directory? It should be located in ``TEMP\discord-rpc\discord-rpc.so``

**Comment by Vatuu** [comment] 2018-01-30 00:07
If you don't reply until tomorrow noon, I'll close this issue as it does not seem important anymore.

**Comment by wyatt-herkamp** [comment] 2018-01-30 16:57
That directory is not created. I am sorry. I forgot.

**Comment by Vatuu** [comment] 2018-01-30 17:16
Try updating to version```0.9-BETA.6```

And tell me if it's still broken.

**Comment by wyatt-herkamp** [comment] 2018-01-30 17:31
Still broken. https://paste.ee/p/GGssI
All files that are in my project folder. https://paste.ee/p/mSHlP

**Comment by Vatuu** [comment] 2018-01-30 19:24
Do you shade the Discord-RPC Artifact?

**Comment by wyatt-herkamp** [comment] 2018-02-01 15:12
Yes

**Comment by Vatuu** [comment] 2018-07-28 18:49
We were completely unable to reproduce this issue, therefore we can only assume it's an issue with your application or your system environment.

This issue will be closed.

**Comment by wyatt-herkamp** [comment] 2018-07-28 18:58
I tried to make a rpc with https://github.com/MinnDevelopment/java-discord-rpc it worked fine.

**Comment by DeJayDev** [comment] 2018-07-28 20:49
That's motivating. I'm going to further investigate by attempting to simulate your desktop environment here. Unlocking this because of my own stupid curiosity.

**Comment by DeJayDev** [comment] 2018-07-28 21:06
Yeah,

The RPC has completely changed and without an updated code sample I can't help any further, though your issue seems related to #16. Please wait for the proper fix to come out.

This issue will be closed due to version mismatch and a fix is set to go out later today.

**Closed as completed by DeJayDev** 2018-07-28 21:06 UTC
Labels: bug
