### ISSUE TITLE
Mac lib not found

### ISSUE THREAD

**Issue by bddvlpr** [Vatuu/discord-rpc#12] opened 2018-04-09 15:57 UTC
As seen in #5 , i'm still getting that same error, even using the latest discord and discord-rpc version.
I'm using maven by the way.

**Comment by Vatuu** [comment] 2018-04-13 23:51
Try to update to the latest version https://github.com/Vatuu/discord-rpc/releases/tag/1.4.3. When the issue still persists, please report it here.

**Comment by bddvlpr** [comment] 2018-04-14 20:57
Thanks for helping, will try out https://github.com/Vatuu/discord-rpc/releases/tag/1.4.3 in a bit.

**Comment by bddvlpr** [comment] 2018-04-14 21:25
Issue still exists.
Stacktrace:
`java.lang.UnsatisfiedLinkError: Unable to load library 'discord-rpc': Native library (darwin/libdiscord-rpc.dylib) not found in resource path ([file:/Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home/jre/lib/charsets.jar, file:/Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home/jre/lib/deploy.jar, file:/Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home/jre/lib/ext/cldrdata.jar, file:/Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home/jre/lib/ext/dnsns.jar, file:/Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home/jre/lib/ext/jaccess.jar, file:/Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home/jre/lib/ext/jfxrt.jar, file:/Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home/jre/lib/ext/localedata.jar, file:/Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home/jre/lib/ext/nashorn.jar, file:/Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home/jre/lib/ext/sunec.jar, file:/Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home/jre/lib/ext/sunjce_provider.jar, file:/Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home/jre/lib/ext/sunpkcs11.jar, file:/Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home/jre/lib/ext/zipfs.jar, file:/Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home/jre/lib/javaws.jar, file:/Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home/jre/lib/jce.jar, file:/Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home/jre/lib/jfr.jar, file:/Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home/jre/lib/jfxswt.jar, file:/Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home/jre/lib/jsse.jar, file:/Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home/jre/lib/management-agent.jar, file:/Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home/jre/lib/plugin.jar, file:/Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home/jre/lib/resources.jar, file:/Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home/jre/lib/rt.jar, file:/Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home/lib/ant-javafx.jar, file:/Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home/lib/dt.jar, file:/Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home/lib/javafx-mx.jar, file:/Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home/lib/jconsole.jar, file:/Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home/lib/packager.jar, file:/Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home/lib/sa-jdi.jar, file:/Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home/lib/tools.jar, file:/Users/stimons/Desktop/Java/Lunix/Lunix-1.12.2/target/classes/, file:/Users/stimons/.m2/repository/org/lwjgl/lwjgl/lwjgl_util/2.9.2/lwjgl_util-2.9.2.jar, file:/Users/stimons/.m2/repository/org/lwjgl/lwjgl/lwjgl/2.9.2/lwjgl-2.9.2.jar, file:/Users/stimons/.m2/repository/org/lwjgl/lwjgl/lwjgl-platform/2.9.2/lwjgl-platform-2.9.2-natives-windows.jar, file:/Users/stimons/.m2/repository/org/lwjgl/lwjgl/lwjgl-platform/2.9.2/lwjgl-platform-2.9.2-natives-linux.jar, file:/Users/stimons/.m2/repository/org/lwjgl/lwjgl/lwjgl-platform/2.9.2/lwjgl-platform-2.9.2-natives-osx.jar, file:/Users/stimons/.m2/repository/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar, file:/Users/stimons/.m2/repository/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar, file:/Users/stimons/.m2/repository/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-linux.jar, file:/Users/stimons/.m2/repository/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar, file:/Users/stimons/.m2/repository/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-osx.jar, file:/Users/stimons/.m2/repository/ca/weblite/java-objc-bridge/1.0.0/java-objc-bridge-1.0.0.jar, file:/Users/stimons/.m2/repository/org/apache/commons/commons-lang3/3.6/commons-lang3-3.6.jar, file:/Users/stimons/.m2/repository/io/netty/netty-all/4.1.9.Final/netty-all-4.1.9.Final.jar, file:/Users/stimons/.m2/repository/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar, file:/Users/stimons/.m2/repository/net/sf/jopt-simple/jopt-simple/4.7/jopt-simple-4.7.jar, file:/Users/stimons/.m2/repository/com/ibm/icu/icu4j/59.1/icu4j-59.1.jar, file:/Users/stimons/.m2/repository/com/google/code/gson/gson/2.8.1/gson-2.8.1.jar, file:/Users/stimons/.m2/repository/com/mojang/authlib/1.5.25/authlib-1.5.25.jar, file:/Users/stimons/.m2/repository/commons-codec/commons-codec/1.10/commons-codec-1.10.jar, file:/Users/stimons/.m2/repository/commons-io/commons-io/2.4/commons-io-2.4.jar, file:/Users/stimons/.m2/repository/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar, file:/Users/stimons/.m2/repository/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar, file:/Users/stimons/.m2/repository/com/google/guava/guava/21.0/guava-21.0.jar, file:/Users/stimons/.m2/repository/com/mojang/realms/1.10.17/realms-1.10.17.jar, file:/Users/stimons/.m2/repository/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar, file:/Users/stimons/.m2/repository/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar, file:/Users/stimons/.m2/repository/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar, file:/Users/stimons/.m2/repository/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar, file:/Users/stimons/.m2/repository/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar, file:/Users/stimons/.m2/repository/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar, file:/Users/stimons/.m2/repository/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar, file:/Users/stimons/.m2/repository/com/paulscode/codecwav/20101023/codecwav-20101023.jar, file:/Users/stimons/.m2/repository/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar, file:/Users/stimons/.m2/repository/tv/twitch/twitch/6.5/twitch-6.5.jar, file:/Users/stimons/.m2/repository/tv/twitch/twitch-platform/6.5/twitch-platform-6.5-natives-windows-32.jar, file:/Users/stimons/.m2/repository/tv/twitch/twitch-platform/6.5/twitch-platform-6.5-natives-windows-64.jar, file:/Users/stimons/.m2/repository/tv/twitch/twitch-platform/6.5/twitch-platform-6.5-natives-osx.jar, file:/Users/stimons/.m2/repository/tv/twitch/twitch-external-platform/4.5/twitch-external-platform-4.5-natives-windows-32.jar, file:/Users/stimons/.m2/repository/tv/twitch/twitch-external-platform/4.5/twitch-external-platform-4.5-natives-windows-64.jar, file:/Users/stimons/.m2/repository/oshi-project/oshi-core/1.1/oshi-core-1.1.jar, file:/Users/stimons/.m2/repository/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar, file:/Users/stimons/.m2/repository/it/unimi/dsi/fastutil/7.1.0/fastutil-7.1.0.jar, file:/Users/stimons/.m2/repository/com/mojang/text2speech/1.10.3/text2speech-1.10.3.jar, file:/Users/stimons/.m2/repository/com/mojang/patchy/1.1/patchy-1.1.jar, file:/Users/stimons/.m2/repository/net/java/dev/jna/jna/4.0.0/jna-4.0.0.jar, file:/Users/stimons/.m2/repository/javax/vecmath/vecmath/1.5.2/vecmath-1.5.2.jar, file:/Users/stimons/.m2/repository/com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.jar, file:/Users/stimons/.m2/repository/org/slick2d/slick2d-core/1.0.2/slick2d-core-1.0.2.jar, file:/Users/stimons/.m2/repository/org/jcraft/jorbis/0.0.17/jorbis-0.0.17.jar, file:/Users/stimons/.m2/repository/org/json/json/20180130/json-20180130.jar, file:/Users/stimons/.m2/repository/org/reflections/reflections/0.9.10/reflections-0.9.10.jar, file:/Users/stimons/.m2/repository/org/javassist/javassist/3.19.0-GA/javassist-3.19.0-GA.jar, file:/Users/stimons/.m2/repository/com/google/code/findbugs/annotations/2.0.1/annotations-2.0.1.jar, file:/Users/stimons/.m2/repository/xyz/baddeveloper/yam/yamlconfig/1.0.0/yamlconfig-1.0.0.jar, file:/Users/stimons/.m2/repository/javassist/javassist/3.12.1.GA/javassist-3.12.1.GA.jar, file:/Users/stimons/.m2/repository/com/github/Vatuu/discord-rpc/1.4.3/discord-rpc-1.4.3.jar, file:/Users/stimons/Library/Application%20Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/181.4203.550/IntelliJ%20IDEA.app/Contents/lib/idea_rt.jar])`

**Comment by Vatuu** [comment] 2018-04-14 23:18
Please check your temp directory. Is a folder being created called discord-rpc containing the apropriate DLL/SO/DYNLIB?

**Comment by bddvlpr** [comment] 2018-04-15 11:16
![image](https://user-images.githubusercontent.com/17461028/38777853-29cab932-40af-11e8-9b4e-a47f1e4e1df0.png)
It has the folder, but nothing inside of it

**Comment by bddvlpr** [comment] 2018-04-22 14:11
bump?

**Comment by Vatuu** [comment] 2018-04-22 16:01
Workin' on it, these errors don't make any sense ._.

**Comment by bddvlpr** [comment] 2018-04-22 16:25
Oh, maybe its a problem with my pom?

**Comment by s5bug** [comment] 2018-04-24 03:38
As far as I can tell, it is an issue with the lib being `osx/discord-rpc.dylib` and not `darwin/libdiscord-rpc.dylib`.

**Comment by bddvlpr** [comment] 2018-04-25 14:11
Not really, as it isn't even downloading them.

**Comment by Vatuu** [comment] 2018-04-25 23:28
If there's any linux user here, I'd ask them to try and run it too, and see if it works.

Right now, it seems like it's a issue with the macOS operating system and it's "nothing else but apple >:c" policy.

**Comment by bddvlpr** [comment] 2018-04-26 15:07
Well, now that i've pulled (because of the pr someone sent), its a different stacktrace.
`DiscordRPC.discordInitialize("idhere", handler, true);`
now results in
```
Caused by: java.lang.NullPointerException
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1792)
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1769)
	at org.apache.commons.io.IOUtils.copy(IOUtils.java:1744)
	at net.arikia.dev.drpc.DiscordRPC.loadDLL(DiscordRPC.java:149)
	at net.arikia.dev.drpc.DiscordRPC.<clinit>(DiscordRPC.java:21)
	... 5 more
```

**Comment by s5bug** [comment] 2018-04-26 15:59
Windows and Linux still work successfully.

**Comment by DeJayDev** [comment] 2018-04-26 17:40
Hey, @StijnSimons. A PR for that problem will go out when I'm home, I know the fix already and I'm not feeling brave enough to code on my phone.

**Comment by bddvlpr** [comment] 2018-04-28 08:54
@DeJayDevelopment Thanks! Hope it works after.

**Comment by DeJayDev** [comment] 2018-04-30 23:10
Hey! We're getting in contact with some Discord Staff to help us triage the issue. We'll keep you posted.

**Comment by OzairP** [comment] 2018-05-08 20:31
I'm not in the IntelliJ plugin area at all, so forgive my ignorance but shouldn't it be `darwin/lib/discord-rpc.dylib`? Right now it's `darwin/libdiscord-rpc.dylib`

```
java.lang.UnsatisfiedLinkError: Unable to load library 'discord-rpc': Native library (darwin/libdiscord-rpc.dylib) not found in resource path
```

**Comment by s5bug** [comment] 2018-05-08 20:33
JNI wants `lib` before Mac libs. Not just intellij (afaik). Calling
load("dir/Name") and not load("dir/File") does this automatically

**Comment by OzairP** [comment] 2018-05-08 20:35
Ah okay, it was a shot in the dark since I saw `lib/` dir. Hope this gets fixed soon, need to brag how much I work on Discord.

**Comment by DeJayDev** [comment] 2018-05-23 11:12
Hi, 

I thought I'd provide a state of the situation here. https://github.com/discordapp/discord-rpc/issues/170

We're still working on a resolution but we believe the issue is something very much out of our hands, and will do whatever we have to so it is okay.

**Comment by DeJayDev** [comment] 2019-02-01 17:05
I haven't forgotten about this issue!

I recently got a MacBook Air and am investigating what can be one on either our library or [discordapp/discord-rpc](https://github.com/discordapp/discord-rpc)'s side. 

For a little bit more insight see my response to [discordapp/discord-rpc#170](https://github.com/discordapp/discord-rpc).

Edit: [A link to the comment.](https://github.com/discordapp/discord-rpc/issues/170#issuecomment-459801039)

**Comment by ilsubyeega** [comment] 2019-10-01 12:57
Any updates?

**Comment by mbouli** [comment] 2020-04-22 22:31
I know this is quite a late response, but I was wondering, is there any fix for this yet?

**Comment by alterie** [comment] 2021-05-13 00:44
any updates?

**Closed as completed** 2021-09-02 22:14 UTC
Labels: bug

**Comment by alterie** [comment] 2021-09-03 02:45
Although I couldn't seem to find any fixes for this, I did find some alternatives.

There's the Discord Game SDK bindings for java and jagrosh's Discord IPC; both of which seem to work find on mac.
